#!/usr/bin/awk -f

# Search classification from douyu main page
# By Jack
# 2016年 04月 09日 星期六 19:33:44 CST

BEGIN {
	stat = 0
	# 0 : unstart
	# 1 : init
	# 2 : find url
	# 3 : find page number
	# 4 : find category name
}
{
	if (stat == 0) {
		pos = match($0, "全部")
		if (RSTART != 0) {
			stat = 1
		}
	} else if (stat == 1) {
		pos = match($0, "data-href=.*?\"")
		if (RSTART != 0) {
			stat = 2
			url = substr($0, RSTART, RLENGTH)
			print url
		}
	} else if (stat == 2) {
		pos = match($0, "[0-9]+")
		if (RSTART != 0) {
			stat = 3
			num = substr($0, RSTART, RLENGTH)
			print num
		}
	} else if (stat == 3) {
		stat = 4;
	} else if (stat == 4) {
		stat = 1
		gsub(" ", "", $0)
		gsub("<.*>", "", $0)
		print $0
		print ""
	}
}
END {
}
