#!/usr/bin/awk -f

# Generate links for each page of each classification
# By Jack
# 2016年 04月 09日 星期六 19:33:44 CST

BEGIN {
	domain = "http://www.douyu.com"
	suffix = "?page=%d&isAjax=1"
	stat = 0
	# 0 : unstart
	# 1 : init
	# 2 : find url
	# 3 : find page number
	# 4 : find category name
}
{
	if (stat == 0) {
		pos = match($0, "/[^\"]*")
		if (RSTART != 0) {
			stat = 1
			url = substr($0, RSTART, RLENGTH)
			print url
			system("mkdir -p ."url)
			system("rm ."url"/*")
		}
	} else if (stat == 1) {
		stat = 2
		num = $0 + 1 - 1;
	} else if (stat == 2) {
		stat = 0
		name = $0
		{
			print name >> "."url"/name";
			for (i=1; i<=num; i++)
			{
				printf(domain""url""suffix"\n", i) >> "."url"/url"
			}
		}
	}
}
END {
}
