#!/bin/bash
#
# tunnel      This shell script creates a tunnel to ln6.
#
# chkconfig: 2345 80 30
# description: Keepalive to ln6 via ssh tunnel.
# processname: tunnel
# config: /etc/tunnel
# pidfile: /var/run/tunnel.pid

### BEGIN INIT INFO
# Provides: 
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop tunnel
# Description: tunnel
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

# Check that we're a privileged user
[ `id -u` = 0 ] || exit 4

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 1

prog="tunnel"

start() {
    # Start daemons.
    ret=0
    echo -n $"Starting $prog: "
    /home/jack/bin/tunnel-daemon >> /var/log/tunnel 2>&1 &
    RETVAL=$?
    echo
    let ret+=$RETVAL
    [ $ret -eq 0 ] && return 0 || return 1
}

stop() {
    # Stop daemons.
    echo -n $"Shutting down $prog: "
    [ -f /var/run/tunnel.pid ] && kill -9 `cat /var/run/tunnel.pid`
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f /var/run/tunnel.pid
    return $RETVAL
}

status -p /var/run/tunnel.pid >/dev/null
running=$?
#echo $running

# See how we were called.
case "$1" in
    start)
	[ $running -eq 0 ] && echo $prog" is already running!" && exit 0
	start
	RETVAL=$?
	;;
    stop)
	if [ $running -eq 0 ]
	then
	    stop
	    RETVAL=$?
	else
	    echo $prog" is not running!"
	    exit 1
	fi
	;;
    restart)
	stop
	start
	RETVAL=$?
	;;
    status)
	if [ $running -eq 0 ]
	then
	    echo $prog" is already running!"
	    echo "PID: "`cat /var/run/tunnel.pid`
	else
	    echo $prog" is not running!"
	fi
	RETVAL=0
	;;
    *)
	echo $"Usage: $0 {start|stop|restart|status}"
	RETVAL=2
esac

exit $RETVAL
