#!/bin/bash

# analyse video page
#
# input: video page
# output: mp4 url

. ./conf

for((try=0, suc=1; try<$MAX & suc!=0;try++))
do
	ret=`$HTTP "$1"`
	$SLEEP
	suc=$?
done
u=`echo $ret | grep -Po "https://cdn.kali.tv/player/tumblr.php\?.*?(?=\")"`

for((try=0, suc=1; try<$MAX & suc!=0;try++))
do
	ret=`$HTTP $u`
	$SLEEP
	suc=$?
done
echo $ret > log
grep -Pom 1 "https://.*?mp4" log > log2
status=$?
head -n 1 log2
rm log log2
exit $status
#u=`echo $ret | grep -Pom 1 "https://.*?mp4"`
#echo ${u% *}
